### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getBoundingClientRect')

### ISSUE THREAD

**Issue by dxhuii** [Akryum/floating-vue#972] opened 2023-06-29 06:50 UTC
<img width="841" alt="image" src="https://github.com/Akryum/floating-vue/assets/2328917/cf2f2c47-f47d-4297-913b-7e9b8383f5ab">

"nuxt": "^3.6.1",
 "floating-vue": "2.0.0-beta.24",

```ts
<script setup lang="ts">
definePageMeta({
  name: 'subject',
  key: route => route.fullPath
})
const route = useRoute()
const subject = useSubjectStore()
const id = $(computedEager(() => route.params.id as string))
await subject.getSubject(id)
const { subjectData: data } = subject
useHead({
  title: () => `${data?.name} | 番组`
})
</script>
````

进入页面有 await 调用接口，会报这个错误。 如果没有。不会报错。麻烦看下。

This error will be reported if the page is entered with an await call interface. If not. No error is reported. Please take a look.

**Comment by antfu** [comment] 2023-06-29 21:13
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-06-29 21:13 UTC
